name: Movecraft-Debug
version: '1.0'
main: de.dertoaster.movecraftdebug.MovecraftDebugPlugin
loader: de.dertoaster.movecraftdebug.init.MovecraftDebugPluginLoader
api-version: '1.21'

#libraries:
#  - fr.skytasul:glowingentities:1.4.3
dependencies:
  #bootstrap:
    # Let's say that RegistryPlugin registers some data that your plugin needs to use
    # We don't need this during runtime, so it's not required in the server section.
    # However, can be added to both if needed
    #RegistryPlugin:
      #load: BEFORE
      #required: true
      #join-classpath: true # Defaults to true
  server:
    Movecraft:
      load: BEFORE
      required: true
      # This means that your plugin will not have access to their classpath
      join-classpath: true
